server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bill-service-route
#          uri: HTTP://127.0.0.1:4000
          uri: lb://bill-service
          predicates:
            - Path=/bills/**
eureka:
  client:
    service-url:
      defaultZone: HTTP://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
